from strands import tool

@tool
def upload_file_local(response_json: str) -> str:
    """Uploads the response generated by the AI to local directory
    Args:
        response_json (str): JSON string containing file paths and contents.

    Returns:
        str: Message confirming which files were saved.
    """
    try:
        response = json.loads(response_json)
        saved_files = []

        for file in response["files"]:
            path = file["path"]
            content = file["content"]
            
            os.makedirs(os.path.dirname(path), exist_ok=True)

            with open(path, "w") as f:
                f.write(content)
            saved_files.append(path)
        
        return f"Successfully saved files: {', '.join(saved_files)}"
    except Exception as e:
        return f"Error saving files: {str(e)}"
