from agents.biz_agent import biz_agent
from agents.design_agent import design_agent
from agents.dev_agent import dev_agent
from agents.test_agent import test_agent
from strands.multiagent import GraphBuilder
from bedrock_agentcore.runtime import BedrockAgentCoreApp
from fastapi.middleware.cors import CORSMiddleware

app = BedrockAgentCoreApp()

try:
    fastapi_app = app.app
except AttributeError:
    fastapi_app = app

fastapi_app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.entrypoint
def main(payload: dict):

    try:

        graph = GraphBuilder()

        # Nodes of the graph
        graph.add_node(biz_agent, "business-analyst")
        graph.add_node(design_agent, "designer")
        graph.add_node(dev_agent, "developer")
        graph.add_node(test_agent, "test-agent")

        # graph.set_entry_point("business-analyst")

        # Edges of the graph
        graph.add_edge("business-analyst", "designer")
        graph.add_edge("designer", "developer")
        graph.add_edge("developer", "test-agent")

        graph = graph.build()

        print("Running the multi-agent graph here!")
        # prompt = input("Enter your prompt: ")
        # prompt = """
        #     Build an API for a collaborative markdown editor where users can:
        #     - create documents
        #     - edit documents
        #     - share documents
        #     - view version history
        # """

        messages = payload.get("messages", [])
        print(messages)
        if not messages:
            return {"error": "Prompt is required"}

        # Extract text from the last message which should be from the user
        prompt = messages[-1].get('text')
        print(f"Prompt extracted: {prompt}")
        # prompt = payload.get("prompt")


        response = graph(prompt)
        
        # Combine outputs from all agents
        combined_text = ""
        
        try:
            biz_text = response.results["business-analyst"].result.message["content"][0]["text"]
            combined_text += f"## Business Analyst\n{biz_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass
            
        try:
            design_text = response.results["designer"].result.message["content"][0]["text"]
            combined_text += f"## Designer\n{design_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass
            
        try:
            dev_text = response.results["developer"].result.message["content"][0]["text"]
            combined_text += f"## Developer\n{dev_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass
            
        try:
            test_text = response.results["test-agent"].result.message["content"][0]["text"]
            combined_text += f"## Test Agent\n{test_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass

        if not combined_text:
            combined_text = "No output generated by agents."

        # text = response.results["business-analyst"].result.message["content"][0]["text"]
        # text = response.results["designer"].result.message["content"][0]["text"]
        # text = response.results["developer"].result.message["content"][0]["text"]
        # text = response.results["test-agent"].result.message["content"][0]["text"]

        # graph_result = graph.run(payload["messages"])
        # outputs = {}

        # for agent_name, node in response.results.items():
        #     try:
        #         outputs[agent_name] = node.result.message["content"][0]["text"]
        #     except:
        #         outputs[agent_name] = "No output"

        return {
            "role": "assistant",
            "content": combined_text
        }

    except Exception as e:
        print(f"Error: {e}")
        return {"error": str(e)}


if __name__ == "__main__":
    print("Server is live at http://localhost:8080")
    app.run()