from fastapi import Request
from graph_agent import create_graph_agent

async def run_all_agent(request: Request):
    try:
        payload = await request.json()
        graph = create_graph_agent()
        if not graph:
            print("Error: Graph agent creation failed.")
            return {"error": "Failed to initialize graph agent"}

        print("Running the multi-agent graph here!")

        messages = payload.get("messages", [])
        print(f"Messages received: {messages}")
        if not messages:
            return {"error": "Prompt is required"}

        # Extract text from the last message which should be from the user
        prompt = messages[-1].get('text')
        print(f"Prompt extracted: {prompt}")

        response = await graph.invoke_async(prompt)
        
        # Combine outputs from all agents
        combined_text = ""
        
        try:
            biz_text = response.results["business-analyst"].result.message["content"][0]["text"]
            combined_text += f"## Business Analyst\n{biz_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass
            
        try:
            design_text = response.results["designer"].result.message["content"][0]["text"]
            combined_text += f"## Designer\n{design_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass
            
        try:
            dev_text = response.results["developer"].result.message["content"][0]["text"]
            combined_text += f"## Developer\n{dev_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass
            
        try:
            test_text = response.results["test-agent"].result.message["content"][0]["text"]
            combined_text += f"## Test Agent\n{test_text}\n\n"
        except (KeyError, IndexError, AttributeError):
            pass

        if not combined_text:
            combined_text = "No output generated by agents."

        return {
            "role": "assistant",
            "content": combined_text
        }

    except Exception as e:
        print(f"Error: {e}")
        return {"error": str(e)}
